### ISSUE TITLE
ApiOperationBase context thread-safe?

### ISSUE THREAD

**Issue by brysonthor** [AuthorizeNet/sdk-java#107]
ApiOperationBase.setMerchantAuthentication(merchantAuthenticationType);
ApiOperationBase.setEnvironment(Environment.SANDBOX);

Is there currently a way to wrap the environment and authentication values into an object that gets used and destroyed per request? The above usage may not be great for those supporting several auth.net accounts. Plz correct me if wrong. thx.

**Comment by georgantasp** [comment]
The only way around using the static methods is to request.setMerchantAuthentication() on each request. And to controller.executeWithApiResponse(environment) on each controller execution.

**Comment by gnongsie** [comment]
Hi all, We are closing this issue as it seems @georgantasp has given the workaround. If you have any other problems regarding this, kindly comment here or open a new issue with the details.
