### ISSUE TITLE
HttpClient extra UTF-8 decode problem?

### ISSUE THREAD

**Issue by richardrega** [AuthorizeNet/sdk-java#108]
A few weeks back a came across a HTTP response map decode exception caused by a product description that has "... 100% ..." on.

The immediate fix was to simply encode this description string before making the API request with  net.authorize.data.Order, but after some digging I found what might be an extra
```
URLDecoder.decode(responseString, HTTP.UTF_8);
```
https://github.com/richardrega/sdk-java/commit/9155b3f8688094ca4b5ba5cc4dc183a71a93beb2

Can anyone else confirm this problem?  I can provide more details if needed.

**Comment by KarthikeyanKumar** [comment]
Hello @richardrega ,

Team is looking into the problem and soon fix will be provided.

Thanks,
Karthikeyan

**Comment by vijayabraj** [comment]
Hi @richardrega  , the URLDecoder.decode is done for reponse if transaction is of type (net.authorize.aim.Transaction or net.authorize.sim.Transaction) which is an old method of 
integrating to our APIs. The java packages net.authorize.aim, net.authorize.sim will be deprecated soon and will not have newer updates.

You can check our [sample codes](https://github.com/AuthorizeNet/sample-code-java/blob/master/src/main/java/net/authorize/sample/PaymentTransactions/ChargeCreditCard.java) repository to see the latest method provided by SDKs which are fully in sync with the latest updates to our APIs (refer: [API reference](https://developer.authorize.net/api/reference/index.html#payment-transactions-charge-a-credit-card)). The [controller](https://github.com/AuthorizeNet/sdk-java/tree/master/src/main/java/net/authorize/api/controller) and [contract](https://github.com/AuthorizeNet/sdk-java/tree/master/src/main/java/net/authorize/api/contract/v1) classes, being autogenerated, have less errors and are actively supported by us.

**Comment by chsriniv9** [comment]
@richardrega closing this issue based on the response from @vijayabraj . Please feel free to re-open if you need any further help.
