### ISSUE TITLE
E00007 : User authentication failed due to invalid authentication values. in auth.net

### ISSUE THREAD

**Issue by JavaNeed** [AuthorizeNet/sdk-java#116]
I am facing exact issue mentioned in the link: https://stackoverflow.com/questions/44325790/e00007-user-authentication-failed-due-to-invalid-authentication-values-in-aut. Please guide/repy.

**Comment by adavidw** [comment]
Looks like this was solved over in StackOverflow. Please go ahead and close this issue at your earliest convenience.

**Comment by JavaNeed** [comment]
I hope to see immediate response from you or your team. Responding so late doesn't make sense.

**Comment by adavidw** [comment]
Sorry about that, but neither GitHub nor StackOverflow are an official channel of support for us. We help out here as much as can and hope to do so more in the future. But, if time is of the essence, you might be better served by our official support channels at https://support.authorize.net/authkb/index?page=home

**Comment by KarthikeyanKumar** [comment]
Hello Team,

It seems like this issue is already addressed.We will be closing this issue.Kindly comment if you have any other problems or you can open a new issue

Thanks,
Karthikeyan
