### ISSUE TITLE
BatchDetails.getSettlementState() returning null due to unexpected element value

### ISSUE THREAD

**Issue by lektran** [AuthorizeNet/sdk-java#117]
Using production, we encountered a few instances of the settlementState element returning the value "settlementError".  This causes BatchDetails.getSettlementState() to return null because the SDK only allows for the values "settledSuccessfully" or "error", as per the API documentation.

`        <batch>
            <batchId>XXXXXXXXXX</batchId>
            <settlementTimeUTC>2017-04-07T02:45:03Z</settlementTimeUTC>
            <settlementTimeLocal>2017-04-06T19:45:03</settlementTimeLocal>
            <settlementState>settlementError</settlementState>
            <paymentMethod>creditCard</paymentMethod>
            <marketType>eCommerce</marketType>
            <product>Card Not Present</product>
        </batch>
`

**Comment by adavidw** [comment]
Good catch! As defined in the [schema](https://apitest.authorize.net/xml/v1/schema/AnetApiSchema.xsd), acceptable values in that element should be _settledSuccessfully_, _settlementError_, or _pendingSettlement_.

I've made the change in the API Reference, although the change won't go live until the next build of the production site (which could be a week or two).
