### ISSUE TITLE
Unexpected Element Error

### ISSUE THREAD

**Issue by pcanurag** [AuthorizeNet/sdk-java#124]
Hi, 
 
I'm getting the following exception thrown from the SDK when attempting to refund a customer's card (this code is running in production). The exception is repeatable and seems associated with a specific card. However, the exception itself seems to arise from parsing of the SOAP response. Has anyone else encountered this issue before? Is there a way to trap the raw SOAP XML response and log  it? 
 
This is running on anet-sdk-java v.1.9.2. on a Solaris machine, java 1.8.0_144, 
 
Thanks,

A. 
 
net.authorize.util.XmlUtility - Exception Details-> Code:'null', Message:'unexpected element 

(uri:"AnetApi/xml/v1/schema/AnetApiSchema.xsd", local:"ErrorResponse"). 

Expected elements are <{AnetApi/xml/v1/schema/AnetApiSchema.xsd}ARBCancelSubscriptionResponse>,
<{AnetApi/xml/v1/schema/AnetApiSchema.xsd}ARBCreateSubscriptionResponse>,
<{AnetApi/xml/v1/schema/AnetApiSchema.xsd}ARBGetSubscriptionListResponse>,
<{AnetApi/xml/v1/schema/AnetApiSchema.xsd}ARBGetSubscriptionResponse>,
<{AnetApi/xml/v1/schema/AnetApiSchema.xsd}ARBGetSubscriptionStatusResponse>,
<{AnetApi/xml/v1/schema/AnetApiSchema.xsd}ARBUpdateSubscriptionResponse>,
<{AnetApi/xml/v1/schema/AnetApiSchema.xsd}authenticateTestResponse>,
<{AnetApi/xml/v1/schema/AnetApiSchema.xsd}createCustomerPaymentProfileResponse>,
<{AnetApi/xml/v1/schema/AnetApiSchema.xsd}createCustomerProfileResponse>,
<{AnetApi/xml/v1/schema/AnetApiSchema.xsd}createCustomerProfileTransactionResponse>,
<{AnetApi/xml/v1/schema/AnetApiSchema.xsd}createCustomerShippingAddressResponse>,
<{AnetApi/xml/v1/schema/AnetApiSchema.xsd}createTransactionResponse>,
<{AnetApi/xml/v1/schema/AnetApiSchema.xsd}decryptPaymentDataResponse>,
<{AnetApi/xml/v1/schema/AnetApiSchema.xsd}deleteCustomerPaymentProfileResponse>,
<{AnetApi/xml/v1/schema/AnetApiSchema.xsd}deleteCustomerProfileResponse>,
<{AnetApi/xml/v1/schema/AnetApiSchema.xsd}deleteCustomerShippingAddressResponse>,
<{AnetApi/xml/v1/schema/AnetApiSchema.xsd}getAUJobDetailsResponse>,
<{AnetApi/xml/v1/schema/AnetApiSchema.xsd}getAUJobSummaryResponse>,
<{AnetApi/xml/v1/schema/AnetApiSchema.xsd}getBatchStatisticsResponse>,
<{AnetApi/xml/v1/schema/AnetApiSchema.xsd}getCustomerPaymentProfileListResponse>,
<{AnetApi/xml/v1/schema/AnetApiSchema.xsd}getCustomerPaymentProfileResponse>,
<{AnetApi/xml/v1/schema/AnetApiSchema.xsd}getCustomerProfileIdsResponse>,
<{AnetApi/xml/v1/schema/AnetApiSchema.xsd}getCustomerProfileResponse>,
<{AnetApi/xml/v1/schema/AnetApiSchema.xsd}getCustomerShippingAddressResponse>,
<{AnetApi/xml/v1/schema/AnetApiSchema.xsd}getHostedPaymentPageResponse>,
<{AnetApi/xml/v1/schema/AnetApiSchema.xsd}getHostedProfilePageResponse>,
<{AnetApi/xml/v1/schema/AnetApiSchema.xsd}getMerchantDetailsResponse>,
<{AnetApi/xml/v1/schema/AnetApiSchema.xsd}getSettledBatchListResponse>,
<{AnetApi/xml/v1/schema/AnetApiSchema.xsd}getTransactionDetailsResponse>,
<{AnetApi/xml/v1/schema/AnetApiSchema.xsd}getTransactionListResponse>,
<{AnetApi/xml/v1/schema/AnetApiSchema.xsd}getUnsettledTransactionListResponse>,
<{AnetApi/xml/v1/schema/AnetApiSchema.xsd}isAliveResponse>,<{AnetApi/xml/v1/schema/AnetApiSchema.xsd}logoutResponse>,
<{AnetApi/xml/v1/schema/AnetApiSchema.xsd}mobileDeviceLoginResponse>,
<{AnetApi/xml/v1/schema/AnetApiSchema.xsd}mobileDeviceRegistrationResponse>,
<{AnetApi/xml/v1/schema/AnetApiSchema.xsd}sendCustomerTransactionReceiptResponse>,
<{AnetApi/xml/v1/schema/AnetApiSchema.xsd}updateCustomerPaymentProfileResponse>,
<{AnetApi/xml/v1/schema/AnetApiSchema.xsd}updateCustomerProfileResponse>,
<{AnetApi/xml/v1/schema/AnetApiSchema.xsd}updateCustomerShippingAddressResponse>,
<{AnetApi/xml/v1/schema/AnetApiSchema.xsd}updateHeldTransactionResponse>,
<{AnetApi/xml/v1/schema/AnetApiSchema.xsd}updateSplitTenderGroupResponse>,
<{AnetApi/xml/v1/schema/AnetApiSchema.xsd}validateCustomerPaymentProfileResponse>'

**Comment by adavidw** [comment]
Hi @pcanurag,

"errorResponse" is the type of response given from our server when an error occurs before the method in the request can be determined. It's an "unknown method" type of error. Evidently the Java SDK does not have code to interpret that kind of response.

You can turn on logging in the SDK and capture the response directly, but in this case that may not help. All the response is trying to tell you is that it didn't understand the request that you sent. What would be more important is to capture the request sent to determine why our server wouldn't be able to understand it.

Any chance you can capture the request that's being sent and post here (minus sensitive details, of course)?

**Comment by pcanurag** [comment]
Ok, will try to send you a capture. But, it appears to be occurring specifically on refund transactions that have already been settled.

**Comment by KarthikeyanKumar** [comment]
Hello @pcanurag ,

Can you please help us in getting the request that is sent (This would help us in diagnosing the issue)?.

Thanks,
Karthikeyan

**Comment by gnongsie** [comment]
Thank you for raising this issue. We have had some releases since the issue was raised, and we hope that these updates have resolved your asks. We are therefore closing this issue. Please raise a new issue, if you’re still facing problems, and we’ll look into it quickly.
