### ISSUE TITLE
Unexpected Element Error

### ISSUE THREAD

**Issue by no-fate** [AuthorizeNet/sdk-java#138]
Hi,

There is error on create customer payment profile. If profile have any property length error then response = null, and 2 log messages from net.authorize.util.XmlUtility.

For example, if you create customer payment profile with bankAccount.routingNumber like '1111-1111-1' you will have this error. And if routingNumber is incorrect, but length is ok, like '111-111-1' then response is not null and this is ok. If routingNumber is correct then curstomer payment profile create, and response is ok.
This affects not only bankAccount.routingNumber, I saw same one on billTo.company too.

anet-sdk-java v.1.9.6
anet-sdk-java v.1.9.7

```
2018-06-20 07:33:14.373  INFO 14744 --- [ool-10-thread-1] net.authorize.util.XmlUtility            :
Exception - while deserializing text:
'<?xml version="1.0" encoding="utf-8"?>
<ErrorResponse xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns="AnetApi/xml/v1/schema/AnetApiSchema.xsd">
  <messages>
    <resultCode>Error</resultCode>
    <message>
      <code>E00003</code>
      <text>The 'AnetApi/xml/v1/schema/AnetApiSchema.xsd:routingNumber' element is invalid - The value XXXXXXXXXXXXX is invalid according to its datatype 'String' - The actual length is greater than the MaxLength value.</text>
    </message>
  </messages>
</ErrorResponse>
'
```
```
2018-06-20 07:33:14.373  WARN 14744 --- [ool-10-thread-1] net.authorize.util.XmlUtility            :
Exception Details->
  Code:'null',
  Message:'unexpected element (uri:"AnetApi/xml/v1/schema/AnetApiSchema.xsd", local:"ErrorResponse"). Expected elements are <{AnetApi/xml/v1/schema/AnetApiSchema.xsd}ARBCancelSubscriptionResponse>,<{AnetApi/xml/v1/schema/AnetApiSchema.xsd}ARBCreateSubscriptionResponse>,<{AnetApi/xml/v1/schema/AnetApiSchema.xsd}ARBGetSubscriptionListResponse>,<{AnetApi/xml/v1/schema/AnetApiSchema.xsd}ARBGetSubscriptionResponse>,<{AnetApi/xml/v1/schema/AnetApiSchema.xsd}ARBGetSubscriptionStatusResponse>,<{AnetApi/xml/v1/schema/AnetApiSchema.xsd}ARBUpdateSubscriptionResponse>,<{AnetApi/xml/v1/schema/AnetApiSchema.xsd}authenticateTestResponse>,<{AnetApi/xml/v1/schema/AnetApiSchema.xsd}createCustomerPaymentProfileResponse>,<{AnetApi/xml/v1/schema/AnetApiSchema.xsd}createCustomerProfileResponse>,<{AnetApi/xml/v1/schema/AnetApiSchema.xsd}createCustomerProfileTransactionResponse>,<{AnetApi/xml/v1/schema/AnetApiSchema.xsd}createCustomerShippingAddressResponse>,<{AnetApi/xml/v1/schema/AnetApiSchema.xsd}createTransactionResponse>,<{AnetApi/xml/v1/schema/AnetApiSchema.xsd}decryptPaymentDataResponse>,<{AnetApi/xml/v1/schema/AnetApiSchema.xsd}deleteCustomerPaymentProfileResponse>,<{AnetApi/xml/v1/schema/AnetApiSchema.xsd}deleteCustomerProfileResponse>,<{AnetApi/xml/v1/schema/AnetApiSchema.xsd}deleteCustomerShippingAddressResponse>,<{AnetApi/xml/v1/schema/AnetApiSchema.xsd}getAUJobDetailsResponse>,<{AnetApi/xml/v1/schema/AnetApiSchema.xsd}getAUJobSummaryResponse>,<{AnetApi/xml/v1/schema/AnetApiSchema.xsd}getBatchStatisticsResponse>,<{AnetApi/xml/v1/schema/AnetApiSchema.xsd}getCustomerPaymentProfileListResponse>,<{AnetApi/xml/v1/schema/AnetApiSchema.xsd}getCustomerPaymentProfileResponse>,<{AnetApi/xml/v1/schema/AnetApiSchema.xsd}getCustomerProfileIdsResponse>,<{AnetApi/xml/v1/schema/AnetApiSchema.xsd}getCustomerProfileResponse>,<{AnetApi/xml/v1/schema/AnetApiSchema.xsd}getCustomerShippingAddressResponse>,<{AnetApi/xml/v1/schema/AnetApiSchema.xsd}getHostedPaymentPageResponse>,<{AnetApi/xml/v1/schema/AnetApiSchema.xsd}getHostedProfilePageResponse>,<{AnetApi/xml/v1/schema/AnetApiSchema.xsd}getMerchantDetailsResponse>,<{AnetApi/xml/v1/schema/AnetApiSchema.xsd}getSettledBatchListResponse>,<{AnetApi/xml/v1/schema/AnetApiSchema.xsd}getTransactionDetailsResponse>,<{AnetApi/xml/v1/schema/AnetApiSchema.xsd}getTransactionListResponse>,<{AnetApi/xml/v1/schema/AnetApiSchema.xsd}getUnsettledTransactionListResponse>,<{AnetApi/xml/v1/schema/AnetApiSchema.xsd}isAliveResponse>,<{AnetApi/xml/v1/schema/AnetApiSchema.xsd}logoutResponse>,<{AnetApi/xml/v1/schema/AnetApiSchema.xsd}mobileDeviceLoginResponse>,<{AnetApi/xml/v1/schema/AnetApiSchema.xsd}mobileDeviceRegistrationResponse>,<{AnetApi/xml/v1/schema/AnetApiSchema.xsd}securePaymentContainerResponse>,<{AnetApi/xml/v1/schema/AnetApiSchema.xsd}sendCustomerTransactionReceiptResponse>,<{AnetApi/xml/v1/schema/AnetApiSchema.xsd}updateCustomerPaymentProfileResponse>,<{AnetApi/xml/v1/schema/AnetApiSchema.xsd}updateCustomerProfileResponse>,<{AnetApi/xml/v1/schema/AnetApiSchema.xsd}updateCustomerShippingAddressResponse>,<{AnetApi/xml/v1/schema/AnetApiSchema.xsd}updateHeldTransactionResponse>,<{AnetApi/xml/v1/schema/AnetApiSchema.xsd}updateMerchantDetailsResponse>,<{AnetApi/xml/v1/schema/AnetApiSchema.xsd}updateSplitTenderGroupResponse>,<{AnetApi/xml/v1/schema/AnetApiSchema.xsd}validateCustomerPaymentProfileResponse>'
```

**Comment by gnongsie** [comment]
Hi,

Thank you for reaching out to us.

- The routing number that you provide in the request must be a numeric string of 9 digits. This is specified as part of the standards set by the ABA.
- This means that you cannot use special characters in the middle of the string.
- When you give **`1111-1111-1`** as input, the length validation is violated. The error message for this is what you get and what you have attached in the issue.
- When you give **`111-111-1`** as input, the string is detected as an invalid ABA routing number, which you will get as an error message.

For the **`billTo.company`**, the expected input is a string, which may include special characters. I do not see the error you are talking about. 

Can you provide me the input that you provided for this field?

Your second error message is an error message for **`ARBCancelSubscriptionResponse`**, but I do not understand how this relates to the question. 

Can you elaborate on how you got this message?

**Comment by no-fate** [comment]
Please check create customer payment profile with bankAccount.routingNumber '1111-1111-1'.
There is no error message. CreateCustomerPaymentProfileResponse is null. Is that ok?

**Comment by no-fate** [comment]
If you do not understand that this issue about I will create example tommorow, my local time is 9 p.m.

**Comment by gnongsie** [comment]
Hi,

That is what I meant. The input **'1111-1111-1'** is wrong. The correct input should be **'111111111'**.

The API expects a numeric string, which cannot include **'-'** or any other special characters.

**Comment by no-fate** [comment]
I understand this is wrong. But why no CreateCustomerPaymentProfileResponse = null after execute CreateCustomerPaymentProfileController.executeWithApiResponse? And why there is log messages about parse error from net.authorize.util.XmlUtility? Shouldn't api return CreateCustomerPaymentProfileResponse with error messages?

**Comment by gnongsie** [comment]
Hi @no-fate , just to keep you updated, I've sent a fix for this and it will be available with the next release. 

You are free to check out [CreateCustomerProfile Sample Code](https://github.com/AuthorizeNet/sample-code-java/blob/master/src/main/java/net/authorize/sample/CustomerProfiles/CreateCustomerProfile.java) for how the current version handles error messages. Of course, this will change when the next version is released to make it more intuitive for the user to handle error messages.

**Comment by no-fate** [comment]
Thank you. I will check it after release.

**Comment by no-fate** [comment]
I am sorry, but version with fix is still not released.

**Comment by gnongsie** [comment]
Hi @no-fate, unfortunately, the PR which I sent did not consider existing use cases. For example, there might be merchants who expect an empty response if there is a validation error.

For now, there does not seem to be any plan to change the behavior of the API in that regard.

As a workaround, please consider [CreateCustomerProfile sample code](https://github.com/AuthorizeNet/sample-code-java/blob/master/src/main/java/net/authorize/sample/CustomerProfiles/CreateCustomerProfile.java) as an example. This is the best that I can come up with for now, so as to satisfy all use cases.

**Comment by no-fate** [comment]
Ok, but I still not think it is proper behaviour, not to parse response from server.

And I work with existing project of your client, so your example didn't help me.

Finally I found restrictions to company name field, on https://developer.authorize.net/api/reference/index.html#customer-profiles-create-customer-payment-profile.
billTo.company -> up to 50 characters.
This field didn't truncate in our side.

Ok, maybe it is not error on your side, not to parse server response. But I think it is.

It is not easy to understand what is going on, if you literally have no error messages, and nothing worth in your production logs.
