### ISSUE TITLE
response error

### ISSUE THREAD

**Issue by liminggui98** [AuthorizeNet/sdk-java#143]
Useing the "Get Transaction List" api, get a error xml:

`<?xml version="1.0" encoding="utf-8"?>
<ErrorResponse xmlns="AnetApi/xml/v1/schema/AnetApiSchema.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <messages>
    <resultCode>Error</resultCode>
    <message>
      <code>E00003</code>
      <text>The 'AnetApi/xml/v1/schema/AnetApiSchema.xsd:transId' element is invalid - The value &amp;#39;&amp;#39; is invalid according to its datatype 'AnetApi/xml/v1/schema/AnetApiSchema.xsd:numericString' - The Pattern constraint failed.</text>
    </message>
  </messages>
</ErrorResponse>`

**Comment by ashtru** [comment]
Hi @liminggui98 

Please share the code you are trying to run (masking login id and transaction key).

GetTransactionList expects _batchId_ as input, and returns transactions in that batch.  For getting the batchId, you can get it by providing the start and end date as inputs to [GetSettledBatchList API](https://developer.authorize.net/api/reference/index.html#transaction-reporting-get-settled-batch-list) for settled transactions. For unsettled transactions, you can use the [GetUnsettledTransactionList](https://developer.authorize.net/api/reference/index.html#transaction-reporting-get-unsettled-transaction-list) API.

You can check the documentation _Request_ tab for [GetTransactionList in the API reference](https://developer.authorize.net/api/reference/index.html#transaction-reporting-get-transaction-list) , for any constraints on inputs.

You can also check out the sample codes for 
- [Get Transaction List](https://github.com/AuthorizeNet/sample-code-java/blob/master/src/main/java/net/authorize/sample/TransactionReporting/GetTransactionList.java).
- [Get Settled Batch List](https://github.com/AuthorizeNet/sample-code-java/blob/master/src/main/java/net/authorize/sample/TransactionReporting/GetSettledBatchList.java)
- [Get Unsettled Transaction List](https://github.com/AuthorizeNet/sample-code-java/blob/master/src/main/java/net/authorize/sample/TransactionReporting/GetUnsettledTransactionList.java)

**Comment by gnongsie** [comment]
If you want to get the details for a single particular transaction, kindly refer to [Get Transaction Details](https://developer.authorize.net/api/reference/index.html#transaction-reporting-get-transaction-details).

As @ashtru has said, GetTransactionList does not expect a transaction ID.

**Comment by chsriniv9** [comment]
@liminggui98 closing this issue considering the steps provided by @ashtru and @gnongsie had this. Please feel free to re-open if further support needed on this issue.
