### ISSUE TITLE
JakartaEE support for authorize.net hava sdk

### ISSUE THREAD

**Issue by pradeeppatelgithub** [AuthorizeNet/sdk-java#211]
Is JakartaEE support available in anet-java-sdk. I am using version 1.9.4 for the java sdk.

https://jakarta.ee/specifications/xml-binding/4.0/
I am trying to upgrade tomcat 10 and it is complaining about the javax.xml.binding. Find below stack trace:
`
java.lang.NoClassDefFoundError: java.lang.NoClassDefFoundError: javax/xml/bind/JAXBException java.lang.NoClassDefFoundError: javax/xml/bind/JAXBException at net.authorize.cim.Transaction.addCustomerProfile(Transaction.java:226) at net.authorize.cim.Transaction.createCustomerProfile(Transaction.java:1061)`
 

Since tomcat is using Jakarte EE  for xml binding and authorize.net sdk is using javax xml binding it is causing the above mentioned error.

**Comment by charlycong** [comment]
We have the same need.

**Comment by sanket2912** [comment]
Anyone found workaroud ?

**Comment by gnongsie** [comment]
We have updated the SDK to use JakartaEE from `v3.0.0`, which will have continued support for Java 9 and higher.
Please note that we have released the final version (`v2.0.7`) for Java 1.8, and we have discontinued support for Java 1.8 and lower.
Closing this issue.
