### ISSUE TITLE
Support createCustomerProfileFromTransactionRequest in the API

### ISSUE THREAD

**Issue by phillipuniverse** [AuthorizeNet/sdk-java#27]
As it stands, I have to duplicate more of the API than I want in order to get this functionality since I cannot extend `net.authorize.cim.Transaction` (no default constructor means I cannot extend it).

I basically had to copy/paste a lot of the communication code in `HttpClient` in order to support this very basic request/response because that class specifically checks for `instanceof net.authorize.cim.Transaction`, that object requires an `net.authorize.cim.TransactionType`, and there is not a `TransactionType` for `createCustomerProfileFromTransactionRequest`.

It seems that all that would be required is to:
1. Add the `createCustomerProfileFromTransactionRequest` enum value to `auth.net.cim.TransactionType`
2. Add a property to `net.authorize.cim.Transaction` for `transId`
3. Provide support for the new enum type serialization in the `net.authorize.cim.Transaction.toXML()` method
4. Provide support for the new enum type in deserialization in `net.authorize.cim.Result`

**Comment by khuder** [comment]
Are there examples or documentation of this on the PHP SDK?

**Comment by khuder** [comment]
Never mind. Ended up just curling to authnet
