### ISSUE TITLE
NPE Result.importResponseCode

### ISSUE THREAD

**Issue by Flamenco** [AuthorizeNet/sdk-java#40]
I have used this SDK for years without issues, but yesterday this came up repeatedly for a particular transaction:

java.lang.NullPointerException
    at net.authorize.aim.cardpresent.Result.importResponseCode(Result.java:166)

I went on authorize.net web site and manually entered the card; It worked fine.

**Comment by brianmc** [comment]
Is it still happening today?  We had several issues with the API yesterday and the failure could be related to those issues.

Thanks

**Comment by jkloian** [comment]
We are having the same issue with ARB.  We too have been using the same code for many, many years:

java.lang.NullPointerException
at net.authorize.arb.Result.importResponseMessages(Result.java:55) 

This started happening 5/27/2015 around 1430 (GMT-7).

The curious thing is that it has been intermittent.  It went away 5/28 and returned today @ 6/1/15 around 1130 (GMT-7).

**Comment by jkloian** [comment]
Is it possible that this is in any way related to the new certs that started rolling out about the same time?

http://community.developer.authorize.net/t5/The-Authorize-Net-Developer-Blog/Production-Certificate-Upgrades-begin-May-27-2015/ba-p/50430

**Comment by brianmc** [comment]
Hi @jkloian,

I think these are related to some recent network issues that we have been experiencing.  See https://status.authorize.net/ for case history, the dates appear to coincide with these reports.

Please accept our apologies for these recent issues, our operations staff have been working around the clock to ensure this is not recurring problem.

**Comment by jkloian** [comment]
Thanks @brianmc.  After verifying our cert store, I found the status URL you just shared and can confirm that all is again well.  Thank you for response.

**Comment by Flamenco** [comment]
The odd thing is that is was only for 1 specific card were were keying.  Was the issue related to a card type, such as a Prepaid card?
