### ISSUE TITLE
The element in namespace 'AnetApi/xml/v1/schema/AnetApiSchema.xsd' has incomplete content.

### ISSUE THREAD

**Issue by JavaHelper** [AuthorizeNet/sdk-java#48]
I am getting following error for the Java code below. Basically I am looking to get the Transaction Details, settled and unsettled..
```The element 'getTransactionDetailsRequest' in namespace 'AnetApi/xml/v1/schema/AnetApiSchema.xsd' has incomplete content. List of possible elements expected: 'refId, transId' in namespace 'AnetApi/xml/v1/schema/AnetApiSchema.xsd'.```

**The Java code for reference**
```
Merchant merchant = Merchant.createMerchant(Environment.SANDBOX, apiLoginID, transactionKey);
		Transaction transaction = merchant.createReportingTransaction(TransactionType.GET_TRANSACTION_DETAILS);
		ReportingDetails details = ReportingDetails.createReportingDetails();
		details.setBatchIncludeStatistics(true);
		transaction.setReportingDetails(details);
		
		Result<Transaction> result = (Result<Transaction>) merchant.postTransaction(transaction);
		System.out.println("Code : "+result.getMessages().get(0).getResultCode());
		System.out.println("Text : "+result.getMessages().get(0).getText());
		
		for (BatchDetails batchDetail : result.getReportingDetails().getBatchDetailsList()) {
			System.out.println("---------------------");
			System.out.println("ID : "+ batchDetail.getBatchId() );
			System.out.println("Settlement State : "+ batchDetail.getSettlementState().value());
			System.out.println("local settlementTime: "+ batchDetail.getSettlementTimeLocal().toString());
		}
```

**Comment by brianmc** [comment]
Hi @JavaHelper we have a sample at https://github.com/AuthorizeNet/sample-code-java/blob/master/src/main/java/net/authorize/sample/TransactionReporting/GetTransactionDetails.java which should help you out.  Let us know if you're still having issues.

**Comment by JavaHelper** [comment]
it looks good. Thanks. I will let you know if I see any issue.
