### ISSUE TITLE
How we can see the list of Settled and Unsettled transactions using anet-java-sdk?

### ISSUE THREAD

**Issue by JavaHelper** [AuthorizeNet/sdk-java#61]
How we can see the list of Settled and Unsettled transactions using anet-java-sdk? Could you please share code snippet?

**Comment by ramittal** [comment]
We have the sample code hosted at:
https://github.com/AuthorizeNet/sample-code-java/blob/master/src/main/java/net/authorize/sample/TransactionReporting/GetSettledBatchList.java
https://github.com/AuthorizeNet/sample-code-java/blob/master/src/main/java/net/authorize/sample/TransactionReporting/GetUnsettledTransactionList.java

You can get to all these sample code from our API Reference page, select the respective API and the choose the specific language your are looking for under "Sample Code" tab:
http://developer.authorize.net/api/reference/#transaction-reporting-get-unsettled-transaction-list

Hope this helps. Pl. let us know if you need any thing more.

**Comment by JavaHelper** [comment]
Thank you. GetSettledBatchList.java seems problem as it gives following error. So we need to add code to accept dates. Could you please update your code and let me know? Please do the needful.

Your GetUnsettledTransactionList.java works fine. 

```
Exception in thread "main" java.lang.NullPointerException: FirstSettlementDate cannot be null
	at net.authorize.api.controller.GetSettledBatchListController.validateRequest(GetSettledBatchListController.java:19)
	at net.authorize.api.controller.base.ApiOperationBase.validate(ApiOperationBase.java:228)
	at net.authorize.api.controller.base.ApiOperationBase.<init>(ApiOperationBase.java:63)
	at net.authorize.api.controller.GetSettledBatchListController.<init>(GetSettledBatchListController.java:11)
	at com.auth.net.commons.authorize.net.GetSettledBatchList.main(GetSettledBatchList.java:25)
```

**Comment by ramittal** [comment]
Thanks for reporting the issue. 
The fix is already in the future branch on GutHub and we going to release fix soon. 
Until then you can use the future branch to test your integration.

**Comment by JavaHelper** [comment]
Thanks. However I'm trying to fixed it from my side by giving firstSettlementDate and lastSettlementDate, but it looks like Authorized.net is not liking format and rejecting it ?

**Comment by JavaHelper** [comment]
Did you get chance to fixed this issue? Could you please guide us in solving the issue? Please do needful.

**Comment by ramittal** [comment]
We are hoping to update the SDK with a new release in coming week, and you will get the updates then. Until then you can use the code from future branch where this issue has been fixed. We will let you know when the release is complete.

**Comment by JavaHelper** [comment]
Thank you for info. I'll be waiting to get new SDK.

**Comment by brianmc** [comment]
1.8.6 Released.  http://search.maven.org/#artifactdetails%7Cnet.authorize%7Canet-java-sdk%7C1.8.6%7Cjar  

  Closing this issue for now.
