### ISSUE TITLE
how can I get / add sample bank details in Authorized.net ?

### ISSUE THREAD

**Issue by JavaHelper** [AuthorizeNet/sdk-java#63]
I'm using DebitBankAccount.java and simply I run it so it gives me following error
how can I get / add sample bank details in Authorized.net ?

```11/05/15 22:24:44,05:  INFO [pool-1-thread-1] (net.authorize.util.LogHelper:24) - Use Proxy: 'false'
Failed Transaction: 2```

```
public class DebitBankAccount {
	public static final String apiLoginId= "CXXXX";
	public static final String transactionKey= "XXXXXXXX";

	public static void main(String[] args) {
		//Common code to set for all requests
		ApiOperationBase.setEnvironment(Environment.SANDBOX);

		MerchantAuthenticationType merchantAuthenticationType  = new MerchantAuthenticationType() ;
		merchantAuthenticationType.setName(apiLoginId);
		merchantAuthenticationType.setTransactionKey(transactionKey);
		ApiOperationBase.setMerchantAuthentication(merchantAuthenticationType);

		// Populate the payment data
		PaymentType paymentType = new PaymentType();
		BankAccountType bankAccountType = new BankAccountType();
		bankAccountType.setAccountType(BankAccountTypeEnum.CHECKING);
		bankAccountType.setRoutingNumber("125000024");
		bankAccountType.setAccountNumber("12345678");
		bankAccountType.setNameOnAccount("John Doe");
		paymentType.setBankAccount(bankAccountType);

		// Create the payment transaction request
		TransactionRequestType txnRequest = new TransactionRequestType();
		txnRequest.setTransactionType(TransactionTypeEnum.AUTH_CAPTURE_TRANSACTION.value());
		txnRequest.setPayment(paymentType);
		txnRequest.setAmount(new BigDecimal(500.00));

		// Make the API Request
		CreateTransactionRequest apiRequest = new CreateTransactionRequest();
		apiRequest.setTransactionRequest(txnRequest);
		CreateTransactionController controller = new CreateTransactionController(apiRequest);
		controller.execute();

		CreateTransactionResponse response = controller.getApiResponse();

		if (response!=null) {

			// If API Response is ok, go ahead and check the transaction response
			if (response.getMessages().getResultCode() == MessageTypeEnum.OK) {

				TransactionResponse result = response.getTransactionResponse();
				if (result.getResponseCode().equals("1")) {
					System.out.println(result.getResponseCode());
					System.out.println("Successful Debit Bank Transaction");
					System.out.println(result.getAuthCode());
					System.out.println(result.getTransId());
				}
				else {
					System.out.println("Failed Transaction: "+result.getResponseCode());
				}
			}
			else{
				System.out.println("Failed Transaction:  "+response.getMessages().getResultCode());
			}
		}
	}
} 
```

**Comment by kikmak42** [comment]
Hi JavaHelper, actually your request is Successful but transaction is declined as the bank credentials you are using must not be valid, the response is :

````
<?xml version="1.0" encoding="UTF-8"?>
<createTransactionResponse xmlns="AnetApi/xml/v1/schema/AnetApiSchema.xsd" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
   <messages>
      <resultCode>Ok</resultCode>
      <message>
         <code>I00001</code>
         <text>Successful.</text>
      </message>
   </messages>
   <transactionResponse>
      <responseCode>2</responseCode>
      <authCode />
      <avsResultCode>P</avsResultCode>
      <cvvResultCode />
      <cavvResultCode />
      <transId>2245347885</transId>
      <refTransID />
      <transHash>AC69AEE7FE11230BDA77FE9B57C81013</transHash>
      <testRequest>0</testRequest>
      <accountNumber>XXXX5678</accountNumber>
      <accountType>eCheck</accountType>
      <errors>
         <error>
            <errorCode>2</errorCode>
            <errorText>This transaction has been declined.</errorText>
         </error>
      </errors>
   </transactionResponse>
</createTransactionResponse>
````

you can add these two lines and see you response in the code itself:

    System.out.println(result.getErrors().getError().get(0).getErrorCode());
    System.out.println(result.getErrors().getError().get(0).getErrorText());
