### ISSUE TITLE
CreateCustomerProfileController disallows creating profile without payment methods

### ISSUE THREAD

**Issue by mkienenb** [AuthorizeNet/sdk-java#64]
We are looking into managing all payment method information using CIM with hosted forms so that credit card information never passes through our services.   However, since `CreateCustomerProfileController`'s validation methods require that PaymentProfiles be provided, as currently implemented, you cannot use hosted forms until a customer profile exists, and you cannot create a customer profile without providing payment information, which forces credit card information to pass through the merchant's services at least once.

I was able to work around the issue by creating my own `FixedCreateCustomerProfileController` which doesn't validate PaymentProfiles or ValidationMode settings, but the correct fix would be to allow empty payment profile values and ValidationMode to be undefined whenever no payment profiles are provided.

    private static class FixedCreateCustomerProfileController extends ApiOperationBase<CreateCustomerProfileRequest, CreateCustomerProfileResponse>  {
        public FixedCreateCustomerProfileController(CreateCustomerProfileRequest apiRequest) {
            super(apiRequest);
        }

        @Override
        protected void validateRequest() {
            CreateCustomerProfileRequest request = this.getApiRequest();

            if ( null == request.getProfile()) throw new NullPointerException("Profile cannot be null");
            // if ( null == request.getRefId()) throw new NullPointerException("RefId cannot be null");
            // if ( null == request.getValidationMode() || ValidationModeEnum.NONE == request.getValidationMode()) throw new NullPointerException("ValidationMode cannot be null");
            // if ( null == request.getProfile().getPaymentProfiles() || 0 == request.getProfile().getPaymentProfiles().size()) throw new NullPointerException("Payment Profile cannot be null or empty");
        }

        @Override
        protected Class<CreateCustomerProfileResponse> getResponseType() {
            return CreateCustomerProfileResponse.class;
        }
    }

I also hit the non-null RefId validation issue, but I see that's been fixed in the Future branch.

**Comment by brianmc** [comment]
We'll make sure this gets into the next release which is upcoming.  You are correct and the SDK should not be making PaymentProfiles or ValidationMode elemenats required.  Thanks for the feedback.

**Comment by brianmc** [comment]
This issue is included in our Future branch now and will ship in the upcoming SDK release.  Thank-you for the Feedback!
