### ISSUE TITLE
No proxy authentication

### ISSUE THREAD

**Issue by sshimanski** [AuthorizeNet/sdk-java#72]
Is it possible to implement proxy authentication? Or at least decouple code from util.HttpClient static calls to use custom configurable instance of HttpClient?

**Comment by brianmc** [comment]
Hi @sshimanski, do you mean the ability to use proxy settings?  We do have that feature and these can be set in the properties file : https://github.com/AuthorizeNet/sdk-java/blob/485aa5be982b1bb56c3358d7891eb91677607efa/anet-java-sdk.properties 

Let us know if you're looking for something over and above these settings.  Thanks.

**Comment by ramittal** [comment]
Rajeev
425-326-0657
Sent with good.com


-----Original Message-----

**Comment by sshimanski** [comment]
Hi. I was talking about proxy authentication - credentials (username/password). Is it possible to add support 'proxy.username' and 'proxy.password' properties?

**Comment by sujaynsg** [comment]
Hi Team, Any update on this issue?

**Comment by gnongsie** [comment]
Hi all, the team is looking into this issue and a fix will be provided soon.

**Comment by vijayraghavan** [comment]
Hi ,

I am using sample code from Anet ( https://github.com/AuthorizeNet/sample-code-java/blob/master/src/main/java/net/authorize/sample/CustomerProfiles/GetCustomerProfile.java ) , and I get a response (ANetApiResponse ) of 407 - Authentication Required , although I added proxy in environment(system obj ) and env variables as per API comments .

Can you please suggest if this issue is similar to what the thread is talking about .

How can I fix it , I am unable to test Java API in local using SANDBOX .

**Comment by gnongsie** [comment]
Hi @vijayraghavan ,

Yes your error does sound familiar to the issue discussed here. However, we do need to understand a little about the environment you are working with.

Can you provide us the version of the SDK that you are working with? And does your proxy server require authentication for you to access the external network?

**Comment by gnongsie** [comment]
Fixing this in PR #133

**Comment by gnongsie** [comment]
Hi @vijayraghavan 

We have indeed sent PRs to address your issue as well as other issues related to proxy settings and authentication. These changes are not in the 1.9.5 version of the SDK.

A new version will be released soon which will have these changes.

**Comment by gnongsie** [comment]
Fix released in SDK v1.9.6

**Comment by vijayraghavan** [comment]
@gnongsie 

I have tries with the new updated version , with Username/Password the code is working .

Thank you .
