### ISSUE TITLE
UTF-8 encoding not set on StringEntity during HttpPost in HttpUtility.java

### ISSUE THREAD

**Issue by erksmaas** [AuthorizeNet/sdk-java#73]
Hi,

I've been trying to migrate to use your SDK and found that I've been unable to send international characters without the request failing.  I've figured out that you are missing encoding the StringEntity in HttpUtility.java.

Can you please change (currently line 68):

httpPost.setEntity(new StringEntity(xmlRequest));

to be:

httpPost.setEntity(new StringEntity(xmlRequest,"UTF-8"));

and it fixes the issue.

Thanks!

**Comment by brianmc** [comment]
Hi @erksmaas, thanks for the feedback.  Since the charset parameter is deprecated I think it's probably best to use the newer contenttype parameter (something like ContentType.TEXT_XML).  We'll definitely look to include that in the next release.

**Comment by brianmc** [comment]
This should be fixed in latest release 1.8.7, thanks again for submitting this issue.

**Comment by erksmaas** [comment]
Great - thanks - I confirmed our test is working using 1.8.7 as well!

On Fri, Feb 26, 2016 at 6:41 AM, Brian McManus <notifications@github.com>
wrote:

> This should be fixed in latest release 1.8.7, thanks again for submitting
> this issue.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/AuthorizeNet/sdk-java/issues/73#issuecomment-189235241>
> .
>



-- 
---

Thank you!

  <http://www.finch.com/en/>

<https://www.linkedin.com/company/finch-llc>
<https://www.facebook.com/finch.ppc/>
<https://mobile.twitter.com/finch_ppc>

*Eric *
*Maas**Founder & CTO*

t: +1-855-275-7772

www.finch.com
The Leader in Programmatic Advertising
