### ISSUE TITLE
Environment not set running example code

### ISSUE THREAD

**Issue by lpavone** [AuthorizeNet/sdk-java#74]
Hi all, 

Anyone having this issue?
I'm just running the Java example code the perform an authorization and getting a null response.
Debugging it I see that controller object has no properly set the environment. The exact message is:
"Environment not set. Set environment using setter or use overloaded method to pass appropriate environment"

I'm setting the environment as the example, didn't change anything:
        ApiOperationBase.setEnvironment(Environment.SANDBOX);

Any idea?

**Comment by brianmc** [comment]
Are you getting that error with the actual sample code https://github.com/AuthorizeNet/sample-code-java/blob/master/src/main/java/net/authorize/sample/PaymentTransactions/AuthorizeCreditCard.java?

What I mean is, if you clone our sample-code-java repo and run that sample is it failing?  That's a good start for troubleshooting.  If that's working but you're still having an issue if you can send your code to developer@authorize.net we can help with the next steps in troubleshooting.

Brian

**Comment by lpavone** [comment]
Hi Brian thanks for take a look.
I have cloned the sample-code-java repo and that's working perfect, I get approval transactions.
However, I have copied the same code AuthorizeCreditCard.java (no changes at all) in a new project and includes the JAR I created using the ANT task and there is when I get this error. I guess should have some problem with the Jar perhaps? 
The version is 1.8.2 and I have generated this following the instructions and having no issues.

**Comment by brianmc** [comment]
@lpavone Are you still having issues setting the environment?    We'll keep this open for a few days to see if there is an update.

**Comment by lpavone** [comment]
I've moved to use the XML API instead of the SDK, so I am not having this
issue anymore, thanks though.



Leonardo Pavone

**Comment by brianmc** [comment]
Thanks for letting us know Leonardo.

**Comment by fazal110** [comment]
I have same issue but i dont know how to get started with xml api in android app
i've moved to use the XML API instead of the SDK, so I am not having this
issue anymore, thanks though.

**Comment by aditya-ongraph** [comment]
I also getting same error with version 2.0.1 

Following line throws error : 
CreateTransactionController transactionController = new CreateTransactionController(apiRequest)

Although I confirmed using debug that environment was set properly.
ApiOperationBase.setEnvironment(Environment.SANDBOX);

Strangely enough, this happened when I copied the implementation code to micro-service from earlier monolith implementation of my project. 
( Same code worked was working on previous application)

Reverting to back to version 2.0.0 worked. 
I upgraded back to 2.0.1 to confirm if this was specific to version but more strangely it started working with 2.0.1 version. 

Anyone have any clue?

**Comment by aditya-ongraph** [comment]
Reverting to back to version 2.0.0 worked.
I upgraded back to 2.0.1 to confirm if this was specific to version but more strangely it started working with 2.0.1 version.

**Comment by kanagalingam** [comment]
Hi,
I am stuck with the same error.

CreateTransactionController controller = new CreateTransactionController(apiRequest);
        controller.execute();

Debugging the controller object, shows the following error

> Environment not set. Set environment using setter or use overloaded method to pass appropriate environment

Any headsup will be really helpful!

**Comment by kanagalingam** [comment]
I was also getting the same error. But the error was not actually with setting environment.

Please find my answer in the below link!

[](https://stackoverflow.com/questions/60650812/authorize-net-java-sdk2-0-1v-environment-not-set-issue/60740806#60740806)
