### ISSUE TITLE
ValidateCustomerPaymentProfile throwing exception.

### ISSUE THREAD

**Issue by Zeeshan7293** [AuthorizeNet/sdk-java#75]
Basically while running ValidateCustomerPaymentProfile.java, I was getting exceptions. This was caused because cardCode and CustomerShippingAddressID were not being set in the sample code. However, the controller validates these fields and throws exception if not found. Following is the piece of code which does the validation in the ValidateCustomerPaymentProfileController:

//validate required fields		
if ( null == request.getCustomerProfileId()) throw new NullPointerException("CustomerProfileId cannot be null");
if ( null == request.getCardCode()) throw new NullPointerException("CardCode cannot be null");
if ( null == request.getCustomerPaymentProfileId()) throw new NullPointerException("CustomerPaymentProfileId cannot be null");
if ( null == request.getCustomerShippingAddressId()) throw new NullPointerException("CustomerShippingAddressId cannot be null");

Now in the API reference nothing is mentioned about which fields are required.

**Comment by brianmc** [comment]
Thanks @Zeeshan7293, the validation is over-strict here.  Can you make a PR  to future for the update?

**Comment by brianmc** [comment]
Merged the PR thanks for the update.
