### ISSUE TITLE
ant build process flawed -- please remove or maintain

### ISSUE THREAD

**Issue by mkienenb** [AuthorizeNet/sdk-java#87]
When the SDK is built from ant, the following error occurs whenever submitting a request:

`SEVERE: Execution error for http post Message: 'java.lang.ArrayStoreException: sun.reflect.annotation.TypeNotPresentExceptionProxy'`

Also, the ant build produces jars labeled "1.8.2" rather than "1.8.9".

Please either remove the Apache Ant build process if it will not be maintained, or update it so that it produces identical results as using Apache Maven.   Thanks!

**Comment by gnongsie** [comment]
Hi @mkienenb, a fix for this has been sent for a merge. It should be available soon.

**Comment by brianmc** [comment]
Change is merged, thanks @gnongsie and @mkienenb

**Comment by mkienenb** [comment]
I rebuilt the sdk today (anet-java-sdk version 1.9.0 hash 2feaf430d62ca387f802d68739a126406854d5b5) using java 1.8 and ant 1.9.4 and I am still getting this error:

`
Ebpp DEBUG [2129565033@qtp0-0 08-29 11:56:42] ApiOperationBase: Creating instance for request:'class net.authorize.api.contract.v1.GetCustomerProfileRequest' and response:'class net.authorize.api.contract.v1.GetCustomerProfileResponse'
Ebpp DEBUG [2129565033@qtp0-0 08-29 11:56:42] ApiOperationBase: Request:'net.authorize.api.contract.v1.GetCustomerProfileRequest@6b32ddee'
Ebpp DEBUG [2129565033@qtp0-0 08-29 11:56:42] ApiOperationBase: Executing Request:'net.authorize.api.contract.v1.GetCustomerProfileRequest@6b32ddee'
Ebpp DEBUG [pool-1-thread-1 08-29 11:56:42] HttpUtility: Posting request to Url: 'https://apitest.authorize.net/xml/v1/request.api'
Ebpp ERROR [2129565033@qtp0-0 08-29 11:56:42] HttpUtility: Execution error for http post Message: 'java.lang.ArrayStoreException: sun.reflect.annotation.TypeNotPresentExceptionProxy'
`
As usual, building with maven instead results in a correctly-working 1.9.1-snapshot jar.

**Comment by mkienenb** [comment]
This is guesswork on my part, but I wonder if perhaps it is due to the javat files being missing since, as I noted in issue 101, the ant build does not include the resources folder.   If I have more time at some point in the future, I will see what happens if the javat files are part of the ant build.

**Comment by mkienenb** [comment]
Still having the same issue reported in 2016 when using the ant build from a May 2020 sdk-java checkout.   Still fixed by building with maven instead of ant.

Issue is closed but not actually resolved.
