### ISSUE TITLE
How to set MarketType and DeviceType

### ISSUE THREAD

**Issue by albertonavarro087** [AuthorizeNet/sdk-java#92]
I was looking at this sample of yours [ChargeCreditCard](https://github.com/AuthorizeNet/sample-code-java/blob/master/src/main/java/net/authorize/sample/PaymentTransactions/ChargeCreditCard.java)
 and comparing it with the one that I have 

`Merchant merchant = Merchant.createMerchant("environment", "loginId", "transactionKey");
 merchant.setMarketType(MarketType.RETAIL);
 merchant.setDeviceType(DeviceType.VIRTUAL_TERMINAL);`

I was wondering how can I set  a MarketType and DeviceType using MerchantAuthenticationType

**Comment by sunnyrajrathod** [comment]
It is not set in MerchantAuthenticationType. You can set it along with amount in [TransactionRequestType](https://github.com/AuthorizeNet/sample-code-java/blob/master/src/main/java/net/authorize/sample/PaymentTransactions/ChargeCreditCard.java#L45).

```
TransRetailInfoType retailInfo = new TransRetailInfoType();
retailInfo.setMarketType(MarketType.RETAIL);
retailInfo.setDeviceType(DeviceType.VIRTUAL_TERMINAL);
txnRequest.setRetail(retailInfo);
```

I hope this helps.

**Comment by albertonavarro087** [comment]
also in your old Transaction Model `Transaction transaction = merchant.createAIMTransaction`
there was an option to set a DuplicateWindow. Where is that option in your new model?

**Comment by gnongsie** [comment]
Hi @albertonavarro087,

In order to set a DuplicateWindow in the new API model, you would need to use TransactionSettings.

To do this through code, you would need to include the following lines:

```
SettingType settingDuplicateWindow= new SettingType();
settingDuplicateWindow.setSettingName("duplicateWindow");
settingDuplicateWindow.setSettingValue("0"); // Time in secs.
        
ArrayOfSetting settingsList = new ArrayOfSetting();
settingsList.getSetting().add(newDuplicateWindow);
        
transaction.setTransactionSettings(settingsList);
```
