### ISSUE TITLE
E00003: invalid child element 'track2'

### ISSUE THREAD

**Issue by albertonavarro087** [AuthorizeNet/sdk-java#93]
Every time I set 
```
PaymentType paymentType = new PaymentType();
CreditCardTrackType creditCardTrackType = new CreditCardTrackType();
creditCardTrackType.setTrack1("track1");
creditCardTrackType.setTrack2("track2");
paymentType.setTrackData(creditCardTrackType);

TransRetailInfoType retailInfo = new TransRetailInfoType();
retailInfo.setMarketType(MarketType.RETAIL.getValue());
retailInfo.setDeviceType(DeviceType.VIRTUAL_TERMINAL.getValue());

        // Create the payment transaction request
TransactionRequestType transactionRequestType = new TransactionRequestType();
transactionRequestType.setTransactionType(TransactionTypeEnum.AUTH_CAPTURE_TRANSACTION.value());
transactionRequestType.setPayment(paymentType);
transactionRequestType.setOrder(orderType);
transactionRequestType.setRetail(retailInfo);
```

I'm getting this error **E00003:The element 'trackData' in namespace 'AnetApi/xml/v1/schema/AnetApiSchema.xsd' has invalid child element 'track2' in namespace 'AnetApi/xml/v1/schema/AnetApiSchema.xsd'.**

```
{
		"code" : "E00003",
		"text" : "An error occurred while parsing the XML request.",
		"description" : "This is the result of an XML parser error.",
		"integration_suggestions": "",
		"other_suggestions": ""
	}
```

if I remove track2 I get transaction Approved

Thanks

**Comment by gnongsie** [comment]
Hi @albertonavarro087, thanks for asking this question.

According to the [ISO/IEC 7813](http://www.iso.org/iso/catalogue_detail.htm?csnumber=43317) and the [ISO/IEC 4909:2006](http://www.iso.org/iso/home/store/catalogue_ics/catalogue_detail_ics.htm?csnumber=43309) standards for financial transaction cards, there are three (3) tracks where data is stored. 

_Of these, track 3 is not standardized for financial transactions and is virtually unused by the major worldwide networks._

Both Track 1 and Track 2 **_individually_** contain enough basic information for processing payment card swipes. You can send 

- Track 1 data, **or** 
- Track 2 data, **or** 
- the card number and expiration date. 

Any combination of those three options results in an error. 

This is an industry standard that has been set by the American Bankers Association (ABA).

Please let us know if you have any further questions.

Gabriel
