### ISSUE TITLE
Issues running SDK on Java 1.5

### ISSUE THREAD

**Issue by teja230** [AuthorizeNet/sdk-java#98]
XMLUtility.java line 73 uses java.lang.String.isEmpty() which is only available starting from java 1.6. So API fails to run on Java 1.5

**Comment by akankaria** [comment]
Thanks for raising this issue. We will recommend you to upgrade to Java 6 or later as Java 5 was end of life long time ago. We will update our README correspondingly.

**Comment by teja230** [comment]
Will do, thanks for the reply
